invisible(lapply(c("rms", "multicore", "plyr"), require, character.only = TRUE))
options(showprogress = FALSE)

cv.lrm <- CallCV(lrm.vars, specs, "lrm")
cv.lrm <- CleanCV(cv.lrm, c("log GDP per cap. + log Pop.", ivar.labels))
cv.lrm.lcwar <- CallCV(lrm.vars, specs.cwar, "lrm")
cv.lrm.cwar <- CleanCV(cv.lrm, c("log GDP per cap. + log Pop. + Civil War", ivar.labels.cwar))
cv.ols <- CallCV(ols.vars, specs, "ols")
cv.ols <- CleanCV(cv.ols, c("log GDP per cap. + log Pop.", ivar.labels))
cv.ols.cwar <- CallCV(ols.vars, specs.cwar, "ols")
cv.ols.cwar <- CleanCV(cv.ols, c("log GDP per cap. + log Pop. + Civil War", ivar.labels.cwar))
cv <- c(cv.lrm, cv.lrm.cwar, cv.ols, cv.ols.cwar)
